--Лабораторная работа 1. Работа с объектами БД
--1.	Установите подключение к ВАШЕЙ БД  - CK_<ВашDLlogin>.
--
--2.	Для выполнения данной лабораторной работы необходима ОБЯЗАТЕЛЬНАЯ проработка самостоятельных заданий 1-1, 1-2, 2-1 и 2-2.
--3.	Создайте в БД схемы "Persons", "Organization", "Location"
create schema "Persons";
create schema "Organization";
create schema "Location";
--Создайте/отредактируйте таблицы БД в соответствии с описанием. 
--В случае если тип данных не указан, его необходимо определить самостоятельно
-- 
--Наименование столбца	Тип данных	Ограничение целостности
--"Persons"."EMPLOYEE"
--id 	int4	NOT NULL, PK
--first_name	varchar(50)	NOT NULL
--last_name	varchar(50)	NOT NULL
--gender	bpchar(1)	NOT NULL, допускаются значения только 'М' или 'Ж'
--birthdate	date	NULL 
--email	varchar(100)	NULL, уникальный (АК1), соответствует шаблону <8 символов (цифры, буквы и точка)>@<любой_домен>.<ru>
--country_of_birth	varchar(50)	NULL, значение по умолчанию 'Россия'
--address	varchar(50)	NULL
--dep_id	????	NULL, FK для связи с таблицей "Organization"."DEPARTMENT" ON DELETE SET NULL ON UPDATE CASCADE
--city_id	????	NULL, FK с параметрами по умолчанию для связи с таблицей "Location"."CITY" 
--job_id	????	NOT NULL, FK с параметрами по умолчанию для связи с таблицей "Persons"."JOB" 
--hiredate	date	NOT NULL, не должен быть больше текущей даты. Значение по умолчанию – текущая дата
--При приеме сотрудника на работу необходимо обеспечить выполнение условия: на момент оформления (hiredate) сотруднику д.б. не менее 20 лет
--"Persons"."JOB"
--id	serial	NOT NULL, PK
--job_title	varchar(20)	NOT NULL
--salary	money	Оклад д.б. в пределах от 20000 до 100000. Значение по умолчанию - 20000
--"Organization"."COMPANY"
--ID	Int,
--столбец идентификации (MINVALUE 0 STEP 1),	NOT NULL, PK
--NAME	NAME	NOT NULL
--ADDRES	bpchar(50)	NULL
--AVG_SALARY	numeric(8, 2)	NULL
--"Organization"."DEPARTMENT"
--ID	int	NOT NUL, PK
--DEPT	bpchar(50)	NOT NUL
--COMPANY_ID	int	NOT NUL, FK для связи с таблицей "Organization"."COMPANY", ON UPDATE CASCADE
--Short_DEPT	bpchar(2)	Вычисляемый столбец – 2 левых символа он наименования подразделения (DEPT)
--"Location"."CITY"
--id	serial	NOT NUL, PK
--city_name	varchar(20	NOT NULL
--country_id	????	NULL, FK для связи с таблицей "Location"."COUNTRY"
--Содержимое столбцов city_name  + country_id д.б. уникальным (АК1)
--"Location"."COUNTRY"
--id	serial	NOT NUL, PK
--country_name	varchar(20)	NOT NUL
CREATE TABLE "Location".COUNTRY (
    id SERIAL PRIMARY KEY,  
    country_name VARCHAR(20) NOT NULL
);
CREATE TABLE "Organization".COMPANY (
    id INT GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY, 
    NAME NAME NOT NULL,  
    ADDRES BPCHAR(50),  
    AVG_SALARY NUMERIC(8, 2)  
);
CREATE TABLE "Persons".JOB (
    id SERIAL PRIMARY KEY, 
    job_title VARCHAR(20) NOT NULL,  
    salary NUMERIC(10, 2) DEFAULT 20000 CHECK (salary >= 20000 AND salary <= 100000) 
);
CREATE TABLE "Location".CITY (
    id SERIAL PRIMARY KEY,  
    city_name VARCHAR(20) NOT NULL, 
    country_id INT, 
    CONSTRAINT unique_city_country UNIQUE (city_name, country_id),
    CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES "Location".COUNTRY(id)
);
CREATE TABLE "Organization".DEPARTMENT (
    ID INT PRIMARY KEY,  
    DEPT BPCHAR(50) NOT NULL,  
    COMPANY_ID INT NOT NULL,  
    Short_DEPT BPCHAR(2) GENERATED ALWAYS AS (LEFT(DEPT, 2)) STORED,  
    CONSTRAINT fk_company FOREIGN KEY (COMPANY_ID) REFERENCES "Organization".COMPANY(ID) ON UPDATE CASCADE
);
CREATE TABLE "Persons".EMPLOYEE (
    id SERIAL PRIMARY KEY,  
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender CHAR(1) NOT NULL CHECK (gender IN ('М', 'Ж')),  
    birthdate DATE, 
    email VARCHAR(100) UNIQUE CHECK (email ~ '^[A-Za-z0-9._%+-]{1,8}@[A-Za-z0-9.-]+\.[Rr][Uu]$'),  
    country_of_birth VARCHAR(50) DEFAULT 'Россия',  
    address VARCHAR(50),  
    dep_id INT, 
    city_id INT, 
    job_id INT NOT NULL,  
    hiredate DATE NOT NULL DEFAULT CURRENT_DATE CHECK (hiredate <= CURRENT_DATE),
    CONSTRAINT chk_age CHECK (AGE(hiredate, birthdate) >= INTERVAL '20 years'),

    CONSTRAINT fk_department FOREIGN KEY (dep_id) REFERENCES "Organization".DEPARTMENT(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES "Location".CITY(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    CONSTRAINT fk_job FOREIGN KEY (job_id) REFERENCES "Persons".JOB(id) ON DELETE SET DEFAULT ON UPDATE CASCADE
);
--
--4.	В таблице "Persons"."EMPLOYEE" измените параметры поддержки ссылочной целостности для внешних ключей:
--a.	FK для связи с "Location"."CITY": ON DELETE SET DEFAULT ON UPDATE CASCADE, значение по умолчанию 0 (ноль)
ALTER TABLE "Persons".EMPLOYEE
    DROP CONSTRAINT IF EXISTS fk_city,
    ADD CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES "Location".CITY(id) ON DELETE SET DEFAULT ON UPDATE CASCADE;
--b.	FK для связи с таблицей "Persons"."JOB": ON DELETE SET DEFAULT ON UPDATE CASCADE, значение по умолчанию 0 (ноль)
   ALTER TABLE "Persons".EMPLOYEE
    DROP CONSTRAINT IF EXISTS fk_job,
    ADD CONSTRAINT fk_job FOREIGN KEY (job_id) REFERENCES "Persons".JOB(id) ON DELETE SET DEFAULT ON UPDATE CASCADE;
--
--5.	В таблице "Location"."CITY" измените параметры поддержки ссылочной целостности для внешнего ключа:
--a.	FK для связи с таблицей "Location"."COUNTRY": ON DELETE NO ACTION ON UPDATE CASCADE
ALTER TABLE "Location".CITY
    DROP CONSTRAINT IF EXISTS fk_country,
    ADD CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES "Location".COUNTRY(id) ON DELETE NO ACTION ON UPDATE CASCADE;
--6.	В таблице "Organization"."DEPARTMENT" для столбца DEPT задайте новое имя -  name
ALTER TABLE "Organization".DEPARTMENT
    RENAME COLUMN DEPT TO name;
--7.	В таблицах "Location"."COUNTRY", "Location"."CITY", "Organization"."DEPARTMENT" и "Organization"."COMPANY" для столбцов name задайте ограничение проверки: допускаются только значения, содержащие буквы.
ALTER TABLE "Location".COUNTRY
    ADD CONSTRAINT chk_country_name CHECK (country_name ~ '^[A-Za-zА-Яа-я\s]+$');

ALTER TABLE "Location".CITY
    ADD CONSTRAINT chk_city_name CHECK (city_name ~ '^[A-Za-zА-Яа-я\s]+$');

ALTER TABLE "Organization".DEPARTMENT
    ADD CONSTRAINT chk_dept_name CHECK (name ~ '^[A-Za-zА-Яа-я\s]+$');

ALTER TABLE "Organization".COMPANY
    ADD CONSTRAINT chk_company_name CHECK (NAME ~ '^[A-Za-zА-Яа-я\s]+$')
--8.	Значения столбцов, содержащих названия Компании, Департамента, Должности и Страны – должны быть уникальны!
ALTER TABLE "Organization".COMPANY
    ADD CONSTRAINT unique_company_name UNIQUE (NAME);

ALTER TABLE "Organization".DEPARTMENT
    ADD CONSTRAINT unique_dept_name UNIQUE (name);

ALTER TABLE "Persons".JOB
    ADD CONSTRAINT unique_job_title UNIQUE (job_title);

ALTER TABLE "Location".COUNTRY
    ADD CONSTRAINT unique_country_name UNIQUE (country_name);
--9.	Создайте ER диаграмму БД
